spring.application.name=battles
server.servlet.context-path=/api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.rest.base-path=/rest
data.file.path=${DATA_FILE_PATH:../scripts/db.json}
